### ISSUE TITLE
Configuring remote access for couchdb 

### ISSUE THREAD

**Issue by franck-serot** [ACRA/acralyzer#74]
Hi Kevin,
I used [1] in order to install Acralyzer on couchdb.
I check the remote access with connectify hostpot.
I noticed a first problem in my local pc : the couchdb server with ip provided by hostpot is not reachable.
I found [2] to solve this problem by changing the configuration of couchdb.
Then, I noticed a second problem with my Andoid handset : the couchdb server with ip provided by hostpot is not reachable.
In add, when I start my HelloWorld Andoird Application wherein a crash is implemented, ACRA library return an exception (see logcat below).
Would you please help mee to solve this second problem ?
Thank you in advance for your response.
Best regards,
Franck

01-26 19:42:42.875: E/ACRA(21619): Failed to send crash report for 1390761756000-approved.stacktrace
01-26 19:42:42.875: E/ACRA(21619): org.acra.sender.ReportSenderException: Error while sending JSON report via Http PUT
01-26 19:42:42.875: E/ACRA(21619):  at org.acra.sender.HttpSender.send(HttpSender.java:228)
01-26 19:42:42.875: E/ACRA(21619):  at org.acra.SendWorker.sendCrashReport(SendWorker.java:179)
01-26 19:42:42.875: E/ACRA(21619):  at org.acra.SendWorker.checkAndSendReports(SendWorker.java:141)
01-26 19:42:42.875: E/ACRA(21619):  at org.acra.SendWorker.run(SendWorker.java:77)
01-26 19:42:42.875: E/ACRA(21619): Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to .. timed out
01-26 19:42:42.875: E/ACRA(21619):  at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)
01-26 19:42:42.875: E/ACRA(21619):  at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:144)
01-26 19:42:42.875: E/ACRA(21619):  at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
01-26 19:42:42.875: E/ACRA(21619):  at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
01-26 19:42:42.875: E/ACRA(21619):  at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
01-26 19:42:42.875: E/ACRA(21619):  at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:670)
01-26 19:42:42.875: E/ACRA(21619):  at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:509)
01-26 19:42:42.875: E/ACRA(21619):  at org.acra.util.HttpRequest.send(HttpRequest.java:152)
01-26 19:42:42.875: E/ACRA(21619):  at org.acra.sender.HttpSender.send(HttpSender.java:225)
01-26 19:42:42.875: E/ACRA(21619):  ... 3 more

Ref 
[1] https://github.com/ACRA/acralyzer/wiki/setup
[2] http://ausmarton.blogspot.fr/2012/02/configuring-remote-access-for-couchdb.html

**Comment by jefioliveira** [comment]
Hi you  changed the couchDB config files default.ini and local.ini, parameter bind_address of 127.0.0.1 to 0.0.0.0 ?
